config/routes.rb
Rails.application.routes.draw do
  resources :access_controls
  resources :profiles
  devise_for :users, :controllers => {:registrations => "registrations", sessions: "sessions"}
  resources :questions
  resources :posts
  resources :uploads
  resources :streams
  resources :comments
  resources :publications
  root 'home#index'
  post '/discussions', to: 'discussions#create'
  get '/comments/discussion_comments/:id', to:'comments#discussion_comments'

  get '/profiles/shares/:id', to:'profiles#shares'
  get '/profiles/educations/:id', to:'profiles#educations'
  get '/profiles/details/:id', to:'profiles#details'
  get '/profiles/connections/:id', to:'profiles#connections'
  get '/profiles/bookmarks/:id', to:'profiles#bookmarks'

  get '/follows/follow', to:'follows#follow'
  get '/follows/unfollow', to:'follows#unfollow'

  get '/interconnects/req', to: 'interconnects#req'
  get '/interconnects/connect', to: 'interconnects#connect'
  get '/interconnects/:id/destroy', to: 'interconnects#destroy'

  get '/likes/like', to:'likes#like'
  get '/likes/dislike', to:'likes#dislike'

  get '/bookmarks/bookmark', to:'bookmarks#bookmark'
  get '/bookmarks/unbookmark', to:'bookmarks#unbookmark'

  get '/shares/share', to:'shares#share'
  get '/shares/unshare', to:'shares#unshare'

  get '/uploads/remoted/:id', to: "uploads#remoted"

  post '/educations', to: 'educations#create'
  get '/educations/:id/destroy', to: 'educations#destroy'

  get '/administration', to: 'administration#index'
  get '/administration/section', to: 'administration#sections'

  post '/assignments', to: "assignments#create"
  get '/assignments/:id/destroy', to: "assignments#destroy"

  get '/notification_settings/change', to: 'notification_settings#change'

  post '/roles', to: "roles#create"
  get '/roles/:id/destroy', to: "roles#destroy"
  get '/roles/change_current_role', to: "roles#change_current_role"
  get '/roles/access/:id', to: "roles#access"
  get '/roles/change_start_point/:id', to: "roles#change_start_point"
  post '/assignments', to: "assignments#create"

  get '/home/more', to: "home#more"

  get '/notifications/more', to: "notifications#more"
  get '/notifications', to: "notifications#index"
  get '/notifications/search', to: "notifications#search"

  get '/profiles/more/1', to: "profiles#more"
  get '/profiles/search/1', to: "profiles#search"

  get '/settings', to: 'settings#index'
  get '/clients/update', to: 'clients#update'
  #get '/users/service', to: 'registrations#service'

  devise_scope :user do
   get "/users/service", to: "registrations#service"
   get "/users/cas_login", to: "sessions#cas_login"
 end

  namespace 'api' do
    namespace 'v1' do
      get '/login', to: 'api#login'
      get '/streams', to: 'api#streams'
      post '/sign_up', to: 'api#sign_up'
      post '/make_post', to: 'api#make_post'
      post '/edit_post', to: 'api#edit_post'
      get '/delete_post', to: 'api#delete_post'
      post '/make_stream', to: 'api#make_stream'
      post '/edit_stream', to: 'api#edit_stream'
      get '/delete_stream', to: 'api#delete_stream'
      get '/likes', to: 'api#likes'
      get '/like', to: 'api#like'
      get '/shares', to: 'api#shares'
      get '/share', to: 'api#share'
      get '/follows', to: 'api#follows'
      get '/follow', to: 'api#follow'
      get '/bookmarks', to: 'api#bookmarks'
      get '/bookmark', to: 'api#bookmark'
    end
    namespace 'v2' do
      get '/likes', to: 'api#likes'
      get '/like', to: 'api#like'
      get '/shares', to: 'api#shares'
      get '/share', to: 'api#share'
      get '/follows', to: 'api#follows'
      get '/follow', to: 'api#follow'
      get '/authorized', to: 'api#authorized'
      get '/bookmarks', to: 'api#bookmarks'
      get '/bookmark', to: 'api#bookmark'
      get '/streams', to: 'api#streams'
      get '/wall', to: 'api#wall'
      get '/view_share/:id', to: 'api#view_share'
      get '/view_stream/:id', to: 'api#view_stream'
      get '/view_discussion/:id', to: 'api#view_discussion'
      get '/view_profile/:id', to: 'api#view_profile'
      get '/view_educations/:id', to: 'api#view_educations'

      get '/login', to: 'api#login'
      post '/sign_up', to: 'api#sign_up'
      post '/check_asset',to: 'api#check_asset'
    end
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  self.primary_key = 'uuid'

  belongs_to :question
  has_many :uploads, :as => :uploadable, :dependent => :destroy

  before_create :set_uuid
  def set_uuid
    self.uuid = SecureRandom.uuid
  end

  def id
    self.uuid
  end

  def self.find(uuid)
    Answer.find_by_uuid(uuid)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_question_answers.html.erb
<div id='question-answers'>
  <div class="col-12 pt-4">
    <%= form_for Answer.new, remote: true do |f|%>
    <% if @upload_ids.blank?%>
    <%= hidden_field_tag :attachments, ''%>
    <%else%>
    <%= hidden_field_tag :attachments, @upload_ids.split(',')%>
    <%end%>
    <%= hidden_field_tag :discussion_id, discussion.id%>
    <%= hidden_field_tag :content%>
    <div id='toolbar' style='display:none;'></div>
    <trix-editor input="content" toolbar="toolbar"></trix-editor>
    <%end%>

    <div class="text-right mt-2 mb-2">
      <button id='submit-btn' type="submit" class="btn btn-sm btn-primary"><%=t :submit%></button>
    </div>
    <script>
      $( "#submit-btn" ).click(function() {
        console.log('clicked');
        $( "#new_comment" ).submit();
      });
    </script>
  </div>
  <script type="text/javascript">
    $(document).ready(function() {
      Trix.config.attachments.preview.caption = {
        name: false,
        size: false
      };

      function uploadAttachment(attachment) {
        var csrfToken = $('meta[name="csrf-token"]').attr('content');
        var file = attachment.file;
        var form = new FormData;
        var endpoint = "/uploads";
        form.append("Content-Type", file.type);
        form.append("file", file);
        form.append("upload[uploadable_type]", 'Comment');
        form.append("upload[uploadable_id]", '0');
        form.append("authenticity_token", window._token);

        xhr = new XMLHttpRequest;
        xhr.open("POST", endpoint, true);
        xhr.setRequestHeader("X-CSRF-Token", csrfToken);

        xhr.upload.onprogress = function(event) {
          var progress = event.loaded / event.total * 100;
          return attachment.setUploadProgress(progress);
        };

        xhr.onload = function() {
          if (this.status >= 200 && this.status < 300) {
            var data = JSON.parse(this.responseText);
            $('#attachments').val($('#attachments').val() + ',' + data.id);
            return attachment.setAttributes({
              url: data.extra
            });
          }
        };

        return xhr.send(form);
      };

      document.addEventListener("trix-attachment-add", function(event) {
        var attachment = event.attachment;
        if (attachment.file) {
          return uploadAttachment(attachment);
        }
      });
    });
  </script>
</div>